logger:
  level: debug
  format: text
  output: stdout

server:
  host: "127.0.0.1"
  port: 8080
  read_timeout: 15s
  write_timeout: 15s
  idle_timeout: 60s
  shutdown_timeout: 10s
  templates_dir: templates
  static_dir: templates/static
  static_url_path: /static/
  cors:
    allowed_origins:
      - "*"
